# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "galois"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Veered"]
  s.date = "2012-06-29"
  s.description = "TODO: longer description of your gem"
  s.email = "lucas@likeness.com"
  s.executables = ["galoisd.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/galoisd.rb",
    "features/galois.feature",
    "features/step_definitions/galois_steps.rb",
    "features/support/env.rb",
    "lib/galois.rb",
    "lib/galois_server.rb",
    "lib/rack_monkey.rb",
    "spec/galois_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Veered/galois"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rack>, ["~> 1.4.1"])
      s.add_development_dependency(%q<sinatra>, ["~> 1.3.2"])
      s.add_development_dependency(%q<unicorn>, ["~> 4.3.1"])
      s.add_development_dependency(%q<redis>, ["~> 3.0.1"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rack>, ["~> 1.4.1"])
      s.add_dependency(%q<sinatra>, ["~> 1.3.2"])
      s.add_dependency(%q<unicorn>, ["~> 4.3.1"])
      s.add_dependency(%q<redis>, ["~> 3.0.1"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rack>, ["~> 1.4.1"])
    s.add_dependency(%q<sinatra>, ["~> 1.3.2"])
    s.add_dependency(%q<unicorn>, ["~> 4.3.1"])
    s.add_dependency(%q<redis>, ["~> 3.0.1"])
  end
end

